# Generated by Django 4.1.7 on 2023-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='district',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
