# Generated by Django 4.1.7 on 2023-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='district',
            field=models.CharField(max_length=100),
        ),
    ]
