# Generated by Django 4.1.7 on 2023-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orders',
            name='apartment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cargo',
            field=models.CharField(choices=[('yurtici', 'Yurtiçi Kargo'), ('aras', 'Aras Kargo'), ('mng', 'MNG Kargo')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='postcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='province',
            field=models.CharField(choices=[('', 'İl'), ('adana', 'Adana'), ('adiyaman', 'Adıyaman'), ('afyonkarahisar', 'Afyonkarahisar'), ('agri', 'Ağrı'), ('aksaray', 'Aksaray'), ('amasya', 'Amasya'), ('ankara', 'Ankara'), ('antalya', 'Antalya'), ('ardahan', 'Ardahan'), ('artvin', 'Artvin'), ('aydin', 'Aydın'), ('balikesir', 'Balıkesir'), ('bartin', 'Bartın'), ('batman', 'Batman'), ('bayburt', 'Bayburt'), ('bilecik', 'Bilecik'), ('bingol', 'Bingöl'), ('bitlis', 'Bitlis'), ('bolu', 'Bolu'), ('burdur', 'Burdur'), ('bursa', 'Bursa'), ('canakkale', 'Çanakkale'), ('cankiri', 'Çankırı'), ('corum', 'Çorum'), ('denizli', 'Denizli'), ('diyarbakir', 'Diyarbakır'), ('duzce', 'Düzce'), ('edirne', 'Edirne'), ('elazig', 'Elazığ'), ('erzincan', 'Erzincan'), ('erzurum', 'Erzurum'), ('eskisehir', 'Eskişehir'), ('gaziantep', 'Gaziantep'), ('giresun', 'Giresun'), ('gumushane', 'Gümüşhane'), ('hakkari', 'Hakkâri'), ('hatay', 'Hatay'), ('igdir', 'Iğdır'), ('isparta', 'Isparta'), ('istanbul', 'İstanbul'), ('izmir', 'İzmir'), ('kahramanmaras', 'Kahramanmaraş'), ('karabuk', 'Karabük'), ('karaman', 'Karaman'), ('kars', 'Kars'), ('kastamonu', 'Kastamonu'), ('kayseri', 'Kayseri'), ('kirikkale', 'Kırıkkale'), ('kirklareli', 'Kırklareli'), ('kirsehir', 'Kırşehir'), ('kilis', 'Kilis'), ('kocaeli', 'Kocaeli'), ('konya', 'Konya'), ('kutahya', 'Kütahya'), ('malatya', 'Malatya'), ('manisa', 'Manisa'), ('mardin', 'Mardin'), ('mersin', 'Mersin'), ('mugla', 'Muğla'), ('mus', 'Muş'), ('nevsehir', 'Nevşehir'), ('nigde', 'Niğde'), ('ordu', 'Ordu'), ('osmaniye', 'Osmaniye'), ('rize', 'Rize'), ('sakarya', 'Sakarya'), ('samsun', 'Samsun'), ('sanliurfa', 'Şanlıurfa'), ('siirt', 'Siirt'), ('sinop', 'Sinop'), ('sivas', 'Sivas'), ('sirnak', 'Şırnak'), ('tekirdag', 'Tekirdağ'), ('tokat', 'Tokat'), ('trabzon', 'Trabzon'), ('tunceli', 'Tunceli'), ('usak', 'Uşak'), ('van', 'Van'), ('yalova', 'Yalova'), ('yozgat', 'Yozgat'), ('zonguldak', 'Zonguldak')], max_length=50),
        ),
    ]
