# Generated by Django 4.1.7 on 2023-08-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0005_alter_orders_address_alter_orders_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='apartment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cargo',
            field=models.CharField(choices=[('yurtici', 'Yurtiçi Kargo'), ('aras', 'Aras Kargo'), ('mng', 'MNG Kargo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
