# Generated by Django 4.1.7 on 2023-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_date_alter_orders_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoice',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
