# Generated by Django 4.1.7 on 2023-09-05 16:12

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.get_upload_path),
        ),
    ]
