# Generated by Django 4.1.7 on 2023-08-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodysize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriename', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(default='')),
                ('createdate', models.DateField()),
                ('image', models.FileField(upload_to='imagechild')),
                ('bodysize', models.ManyToManyField(to='products.bodysize')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colors')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.genders')),
                ('subcategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='products.categories')),
                ('topcategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imagechild')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='gender',
            field=models.ManyToManyField(to='products.genders'),
        ),
        migrations.AddField(
            model_name='categories',
            name='topcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.categories'),
        ),
    ]
