# Generated by Django 4.1.7 on 2023-09-01 11:13

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to=products.models.get_upload_path),
        ),
    ]
