# Generated by Django 4.1.7 on 2023-09-01 12:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(upload_to=products.models.get_upload_path_IMAGESINLINE),
        ),
        migrations.AlterField(
            model_name='products',
            name='createdate',
            field=models.DateTimeField(),
        ),
    ]
