# Generated by Django 4.1.7 on 2023-09-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimages_image_alter_products_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='products.categories'),
        ),
    ]
