# Generated by Django 4.1.7 on 2023-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_slug_alter_products_subcategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
