# Generated by Django 4.1.7 on 2023-09-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoriename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
